### ISSUE TITLE
原始用户id

### ISSUE THREAD

**Issue by lawRossi** [csuldw/AntSpider#9]
想加上用户信息构建一个推荐数据集测试推荐算法，方便的话麻烦提供一下原始用户id，谢谢。

**Comment by csuldw** [comment]
数据已整理，文章末尾有分享，谢谢

https://mp.weixin.qq.com/s?__biz=MzAxNTU0NDQ4NQ==&mid=2247484088&idx=1&sn=894c3f335bf7f2a6d4df03f2056cdec5&chksm=9b833b72acf4b264e91b821c84d7cf0c7d8032b2b42b2d7539c2a31069da6476bb3c0d61e211&token=518181550&lang=zh_CN#rd
